---
target: octeon/generic

target__packages__to_merge:
  - naywatch

# Somehow OpenWRT has messed up the name of resulting imagebuilder
# for target octeon. Fixing it here
imagebuilder: https://downloads.openwrt.org/{{ 'snapshots' if openwrt_version == 'snapshot' else 'releases/' ~ openwrt_version }}/targets/{{ target }}/openwrt-imagebuilder-{{ openwrt_version ~ '-' if openwrt_version != 'snapshot' else '' }}octeon.Linux-x86_64.tar.xz
