---
target: "mediatek/filogic"
brand_nice: GL.iNet
model_nice: GL-MT6000 (Flint 2)

dsa_ports:
  - lan1
  - lan2
  - lan3
  - lan4
  - lan5
  - eth1

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi+1
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi
    ifname_hint: wlan2
