---
target: ath79/generic

# PoE port is eth1, 2nd port is eth0
# override port in host_vars if required
int_port: eth1

wireless_devices:
  - name: 11g_standard
    hwmode: 11g
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
