---
target: ath79/nand
brand_nice: GL.iNet
model_nice: GL-AR300M NOR

openwrt_version: 24.10-SNAPSHOT

int_port: eth0

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
