---
target: ipq40xx/generic

model__packages__to_merge:
  - "-kmod-ath10k-ct -ath10k-firmware-qca4019-ct"
  - "kmod-ath10k ath10k-firmware-qca4019"

switch_ports: 6
switch_int_port: 0
switch_ignore_ports: [1, 2, 3]
# WAN port is hardwired to VLAN2. ignore

int_port: eth0

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: soc/40000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/soc/a000000.wifi
    ifname_hint: wlan2
  - name: 11a_mesh
    band: 5g
    htmode_prefix: VHT
    path: platform/soc/a800000.wifi
    ifname_hint: mesh5
