---
target: mediatek/filogic
openwrt_version: 24.10-SNAPSHOT
brand_nice: OpenWrt
model_nice: One

dsa_ports:
  - eth0
  - eth1

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi+1
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi
    ifname_hint: wlan2
