---
target: ath79/generic
brand_nice: COMFAST
model_nice: CF-EW72
version_nice: v1

openwrt_version: 24.10-SNAPSHOT

int_port: eth0

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
