---
target: "mediatek/filogic"
brand_nice: Cudy
model_nice: TR3000
version_nice: v1

openwrt_version: 24.10-SNAPSHOT

dsa_ports:
  - lan
  - wan

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi+1
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HE
    path: platform/soc/18000000.wifi
    ifname_hint: wlan2
