---
target: ath79/generic
brand_nice: TP-Link
model_nice: CPE210
version_nice: v3

int_port: eth0

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2

leds:
  - name: LAN
    sysfs: green:lan
    trigger: netdev
    mode: link tx rx
    dev: eth0
  - name: rssilow
    sysfs: green:link1
    trigger: rssi
    iface: wlan0
    minq: 1
    maxq: 100
  - name: rssimediumlow
    sysfs: green:link2
    trigger: rssi
    iface: wlan0
    minq: 30
    maxq: 100
  - name: rssimediumhigh
    sysfs: green:link3
    trigger: rssi
    iface: wlan0
    minq: 60
    maxq: 100
  - name: rssihigh
    sysfs: green:link4
    trigger: rssi
    iface: wlan0
    minq: 80
    maxq: 100
