---
target: ramips/mt7621
brand_nice: GL.iNet
model_nice: GL-MT1300 (Beryl)
version_nice: v1

dsa_ports:
  - lan1
  - lan2
  - wan

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: 1e140000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0+1
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: 1e140000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0
    ifname_hint: wlan2
