---
target: ath79/generic
brand_nice: TP-Link
model_nice: CPE210
version_nice: v2

int_port: eth0

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
