---
override_target: "ubnt_nanostation-m-xw"
target: ath79/generic
brand_nice: Ubiquiti
model_nice: Nanostation M5
version_nice: XW

int_port: eth1

low_mem: true

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan5
    antenna_gain: 12

poe_ports:
  - name: PoE Passthrough
    gpio_pin: 2
    value: 0
