---
target: mediatek/filogic
brand_nice: Cudy
model_nice: WR3000S
version_nice: v1

dsa_ports:
  - wan
  - lan1
  - lan2
  - lan3
  - lan4

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: HE
    path: platform/18000000.wifi+1
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HE
    path: platform/18000000.wifi
    ifname_hint: wlan2