---
target: ath79/generic
brand_nice: Ubiquiti
model_nice: UniFi AC Mesh

model__packages__to_merge:
  - "-kmod-ath10k-ct -ath10k-firmware-qca988x-ct"
  - "kmod-ath10k ath10k-firmware-qca988x"

int_port: eth0

wireless_devices:
  - name: 11a_standard
    band: 5g
    htmode_prefix: VHT
    path: pci0000:00/0000:00:00.0
    ifname_hint: wlan5
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2
