---

# TODO: delete these old addresses:
#       - mesh: 10.230.3.164/...

ipv6_prefix: '2001:bf7:820:800::/56'

# mgmt: 10.31.154.112/28
# mesh: 10.31.160.240/28
# dhcp: 10.230.39.0/24
networks:

  - vid: 10
    role: mesh
    name: mesh_rhnk
    ipv6_subprefix: -10
    prefix: 10.31.160.241/32

  - vid: 20
    role: mesh
    name: mesh_ap1
    ipv6_subprefix: -20
    prefix: 10.31.160.242/32
    mesh_ap: rixbox-ap1
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 21
    role: mesh
    name: mesh_ap2
    ipv6_subprefix: -21
    prefix: 10.31.160.243/32
    mesh_ap: rixbox-ap2
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 22
    role: mesh
    name: mesh_ap3
    ipv6_subprefix: -22
    prefix: 10.31.160.244/32
    mesh_ap: rixbox-ap3
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    ipv6_subprefix: 40
    prefix: 10.230.39.0/24
    assignments:
      rixbox-core: 1
    inbound_filtering: true
    enforce_client_isolation: true

  - vid: 42
    role: mgmt
    gateway: 1
    dns: 1
    ipv6_subprefix: 42
    prefix: 10.31.154.112/28
    assignments:
      rixbox-core: 1
      rixbox-ap1: 2
      rixbox-ap2: 3
      rixbox-ap3: 4
      # AirOS LiteBeam RHNK
      rixbox-rhnk: 5

location__channel_assignments_11a_standard__to_merge:
  rixbox-ap1: 44-20
  rixbox-ap2: 48-20
  rixbox-ap3: 40-20
