---
ipv6_prefix: '2001:bf7:750:3200::/56'

# Kiehl71 got following prefixes:
# Router: 10.31.178.192/26
# --DHCP: 10.31.178.192/27
# --MESH: 10.31.178.224/28
# --MGMT: 10.31.178.240/28

networks:
  # DHCP
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.178.192/27
    ipv6_subprefix: 0
    assignments:
      kiehl71-core: 1

  # MESH - 5 GHz 802.11s
  - vid: 20
    role: mesh
    name: mesh_11s_5ghz
    prefix: 10.31.178.224/32
    ipv6_subprefix: -1
    mesh_ap: kiehl71-core
    mesh_radio: 11a_standard
    mesh_iface: mesh

  # MESH - 2.4 GHz 802.11s
  - vid: 21
    role: mesh
    name: mesh_11s_2ghz
    prefix: 10.31.178.225/32
    ipv6_subprefix: -2
    # make mesh_metric(s) for 2GHz worse than 5GHz
    mesh_metric: 1024
    mesh_metric_lqm: ['default 0.8']
    mesh_ap: kiehl71-core
    mesh_radio: 11g_standard
    mesh_iface: mesh

  # MGMT
  - vid: 42
    role: mgmt
    prefix: 10.31.178.240/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      kiehl71-core: 1

# AP-id, wifi-channel, bandwidth, txpower
location__channel_assignments_11a_standard__to_merge:
  kiehl71-core: 36-20

# AP-id, wifi-channel, bandwidth, txpower
location__channel_assignments_11g_standard__to_merge:
  kiehl71-core: 13-20
