---

snmp_devices:
  - hostname: simeon-mgh
    address: 10.31.104.131
    snmp_profile: airos_8

  - hostname: simeon-nord
    address: 10.31.104.132
    snmp_profile: airos_8

  - hostname: simeon-emma
    address: 10.31.104.133
    snmp_profile: airos_6

  - hostname: simeon-rhxb
    address: 10.31.104.134
    snmp_profile: airos_8
