---
- name: Running bbb-configs
  hosts: all
  connection: local
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: cfg_openwrt }
  vars:
    git_revision: "{{ lookup('pipe', 'git rev-parse --short HEAD') }}"
