---
- name: Create rc.d directory
  ansible.builtin.file:
    state: directory
    path: "{{ configs_dir }}/etc/rc.d"
    mode: "755"

- name: Enable replace_secrets symlink
  ansible.builtin.file:
    src: "../init.d/replace_secrets"
    dest: "{{ configs_dir }}/etc/rc.d/S15replace_secrets"
    state: link
  when: role == "corerouter" or role == "ap"
