---
- name: Create rc.d directory
  file:
    state: directory
    path: "{{ configs_dir }}/etc/rc.d"
    mode: "755"

- name: Enable replace_secrets symlink
  file:
    src: "../init.d/replace_secrets"
    dest: "{{ configs_dir }}/etc/rc.d/S15replace_secrets"
    state: link
  when: role == "corerouter" or role == "ap"

- name: Enable sysfs-overrides symlink
  file:
    src: "../init.d/sysfs-overrides"
    dest: "{{ configs_dir }}/etc/rc.d/S12sysfs-overrides"
    state: link
  when:
    - (sysfs_overrides | default([]) | length > 0) or (cpu_governor is defined)
