---
- name: "Define MGMT prefix number"
  set_fact:
    mgmt_network: "{{ networks | selectattr('role', 'equalto', 'mgmt') | first }}"

- name: "Set ansible ssh target from IPv6 Prefix"
  set_fact:
    ansible_ssh_host: "{{ ipv6_prefix | ipsubnet('64', mgmt_network['ipv6_subprefix']) | ipaddr(1) | ipaddr('address') }}"
    ansible_user: root

- name: "Transfer image to remote host:"
  changed_when: false
  command: scp -o StrictHostKeyChecking=no {{ image }} {{ ansible_user }}@[{{ ansible_ssh_host }}]:/tmp/

- name: "Launch Sysupgrade"
  changed_when: false
  command: ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_ssh_host }} "sysupgrade -n /tmp/{{ inventory_hostname }}.bin"
