---
- name: Add uplink watchdog config
  template:
    src: "{{ role_path }}/templates/common/config/watchcat.j2"
    dest: "{{ configs_dir }}/etc/config/watchcat"
    mode: "644"

- name: Add uplink watchdog script to restart the DSL modem
  copy:
    content: |
      #!/bin/sh
      logger -t uplink-watchdog "restarting the DSL modem"
      /etc/init.d/dsl_control restart
    dest: "{{ configs_dir }}/etc/uplink-watchdog-dsl.sh"
    mode: "755"
  when: dsl is defined
