#!/usr/bin/env bash

case "$1" in
--host)
    echo '{}'
    ;;
--list)
    HOSTS=$(for i in host_vars/*; do echo -ne "$i\c" | awk -F'/' '{printf "\""$2"\", "}'; done)
    HOSTS="${HOSTS::-2}"
    cat <<EOF
{
    "all": {
	"hosts": [ $HOSTS ]
    }
}
EOF
    ;;
esac
