---
ipv6_prefix: "2001:bf7:830:a100::/56"

# B0russia got following prefixes:
# Router: 10.31.142.96/27
# --MGMT: 10.31.142.96/28
# --MESH: 10.31.142.112/28
# --DHCP: 10.31.146.0/25

networks:
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.146.0/25
    ipv6_subprefix: 0
    assignments:
      b0russia-core: 1

  - vid: 20
    role: mesh
    name: mesh_core_5ghz
    prefix: 10.31.142.112/32
    ipv6_subprefix: -1
    mesh_ap: b0russia-core
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.3           # use wireguard as uplink

  - vid: 42
    role: mgmt
    prefix: 10.31.142.96/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      b0russia-core: 1

  - vid: 50
    untagged: true
    name: uplink
    role: uplink
    tunnel_wan_ip: 192.168.2.2/24
    tunnel_wan_gw: 192.168.2.1
    tunnel_connections: 2
    tunnel_timeout: 600
    tunnel_mesh_prefix_ipv4: 10.31.142.120/29
