#!/bin/sh /etc/rc.common
# Script which replaces all secrets, which inline reference to files
# It has to run before the secrets are being used, obviously

START=15

log() {
  logger -t replace_secrets "$1"
}


boot() {
  log "Iterating over uci config - Checking for tasks"
  for i in $(uci show | grep "'file:"); do
    uci_key=$(echo $i | awk -F'=' '{print $1}')
    uci_value=$(echo $i | awk -F'=' '{print $2}')

    action=$(echo $uci_value | awk -F"[':]" '{print $2}')
    parameter=$(echo $uci_value | awk -F"[':]" '{print $3}')
    if [ $action == 'file' ]; then
      new_value=$(cat $parameter)
      log "Replace $uci_key ($uci_value) by value read from file $parameter"
     uci set "$uci_key=$new_value"
     uci commit
    fi
  done
  log "Done"
}
