---

collectd_snmp_profiles:
  af60:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.11.1.1.2.1
    rf_width:
      Type: frequency
      TypeInstance: "Channel Width (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.11.1.1.3.1
    rf_sta_distance:
      PluginInstance: distance
      Type: gauge
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.11.1.3.1.14
      Values: .1.3.6.1.4.1.41112.1.11.1.3.1.15
    rf_sta_signal:
      Type: signal_power
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.11.1.3.1.14
      Values: .1.3.6.1.4.1.41112.1.11.1.3.1.3
    rf_sta_snr:
      Type: snr
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.11.1.3.1.14
      Values: .1.3.6.1.4.1.41112.1.11.1.3.1.4
    rf_sta_rx_capacity:
      Type: bitrate
      PluginInstance: rx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.11.1.3.1.14
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.11.1.3.1.7
    rf_sta_tx_capacity:
      Type: bitrate
      PluginInstance: tx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.11.1.3.1.14
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.11.1.3.1.8

  airos_8:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.4.1.1.4.1
    rf_sta_distance:
      PluginInstance: distance
      Type: gauge
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.5.1
    rf_sta_signal:
      Type: signal_power
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.3.1
    rf_sta_cinr:
      Type: snr
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.16.1
    rf_sta_rx_capacity:
      Type: bitrate
      PluginInstance: rx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.18.1
    rf_sta_tx_capacity:
      Type: bitrate
      PluginInstance: tx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.17.1
    rf_sta_tx_latency:
      Type: latency
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.20.1

  # Collectd will throw a noSuchName error every Interval for every Value
  # when no Station is connected to a AP
  airos_6:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.41112.1.4.1.1.4.1
    rf_sta_signal:
      Type: signal_power
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.3.1
    rf_sta_noise:
      Type: signal_noise
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.4.1
    rf_sta_distance:
      PluginInstance: distance
      Type: gauge
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.5.1
    rf_sta_ccq:
      Type: signal_quality
      Table: true
      TypeInstancePrefix: "CCQ (%)  "
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Values: .1.3.6.1.4.1.41112.1.4.7.1.6.1
    rf_sta_rx_capacity:
      Type: bitrate
      PluginInstance: tx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.11.1
    rf_sta_tx_capacity:
      Type: bitrate
      PluginInstance: tx
      Table: true
      TypeInstanceOID: .1.3.6.1.4.1.41112.1.4.7.1.2.1
      Scale: 1000
      Values: .1.3.6.1.4.1.41112.1.4.7.1.12.1

  # For PtMP APs we should define another profile which provides rf info per station
  mikrotik_60g:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0
    rf_freq:
      Type: frequency
      TypeInstance: "Frequency (MHz)"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.6.1
    rf_mcs:
      Type: gauge
      TypeInstance: "MCS Level"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.7.1
    rf_quality:
      Type: signal_quality
      TypeInstance: "Percent"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.8.1
    rf_tx_sector:
      Type: gauge
      TypeInstance: "TX Sector"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.9.1
    rf_rssi:
      Type: signal_power
      TypeInstance: "RSSI (dBm)"
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.12.1
    rf_phy_rate:
      Type: bitrate
      TypeInstance: "TX Bitrate"
      Scale: 1000000
      Values: .1.3.6.1.4.1.14988.1.1.1.8.1.13.1

  swos:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    temp:
      Type: temperature
      TypeInstance: Celsius
      Table: false
      Scale: 0.1
      Values: .1.3.6.1.4.1.14988.1.1.3.11.0

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Scale: 0.001
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.5

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  # The CSS610-Series only runs SwOS Lite which have different OIDs at least for health
  swos_lite:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    temp:
      Type: temperature
      TypeInstance: Celsius
      Table: false
      Values: .1.3.6.1.4.1.14988.1.1.3.100.1.3.52.0

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Scale: 0.001
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.5

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  routeros:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    temp:
      Type: temperature
      TypeInstance: Celsius
      Table: false
      Scale: 0.1
      Values: .1.3.6.1.4.1.14988.1.1.3.10.0

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Scale: 0.001
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.5

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.2.2.1.2
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  edgeswitch:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Scale: 0.001
      Values: .1.3.6.1.2.1.2.2.1.5

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  edgerouter:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.25.1.1.0

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Scale: 0.001
      Values: .1.3.6.1.2.1.2.2.1.5

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  tplink:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Scale: 0.001
      Values: .1.3.6.1.2.1.2.2.1.5

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  zyxel:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Scale: 0.001
      Values: .1.3.6.1.2.1.2.2.1.5

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"

  netgear:
    sys_uptime:
      Type: uptime
      TypeInstance: days
      Table: false
      Scale: 1.15740740741e-07
      Values: .1.3.6.1.2.1.1.3.0

    if_oper_status:
      Type: gauge
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: .1.3.6.1.2.1.2.2.1.8

    if_speed:
      Type: bitrate
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Scale: 0.001
      Values: .1.3.6.1.2.1.2.2.1.5

    if_errors:
      Type: if_errors
      TypeInstanceOID: .1.3.6.1.2.1.31.1.1.1.18
      Table: true
      Values: ".1.3.6.1.2.1.2.2.1.14\" \".1.3.6.1.2.1.2.2.1.20"
