---

snmp_devices:
  - hostname: chris-bht
    address: 10.230.18.3
    snmp_profile: airos_6

  - hostname: chris-tub
    address: 10.230.18.4
    snmp_profile: airos_6

  - hostname: chris-n-5ghz
    address: 10.230.18.5
    snmp_profile: airos_6

  - hostname: chris-o-5ghz
    address: 10.230.18.6
    snmp_profile: airos_6

  - hostname: chris-s-5ghz
    address: 10.230.18.7
    snmp_profile: airos_6

  - hostname: chris-w-5ghz
    address: 10.230.18.8
    snmp_profile: airos_6
