---
ipv6_prefix: "2001:bf7:750:3600::/56"

networks:
  - vid: 10
    role: mesh
    name: mesh_emma
    prefix: 10.31.18.130/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 11
    role: mesh
    name: mesh_simeon
    prefix: 10.31.19.8/32
    ipv6_subprefix: -2
    mesh_metric: 256
    ptp: true

  - vid: 12
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.38.204/32
    ipv6_subprefix: -3
    mesh_metric: 256
    ptp: true

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.102.128/25
    ipv6_subprefix: 0
    assignments:
      koepi-core: 1

  - vid: 41
    role: dhcp
    name: home
    no_corerouter_dns_record: true
    inbound_filtering: true
    enforce_client_isolation: false
    prefix: 10.31.123.0/25
    ipv6_subprefix: 1
    assignments:
      koepi-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.102.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 2
    assignments:
      koepi-core: 1
      koepi-poe: 2
      koepi-emma: 3
      koepi-rhnk: 4
      koepi-simeon: 5
      koepi-ap1: 10
      koepi-ap2: 11
      koepi-ap3: 12
      koepi-ap4: 13
      koepi-ap5: 14
      koepi-trailer1: 20
      koepi-trailer2: 21
      koepi-front: 22

location__channel_assignments_11a_standard__to_merge:
  koepi-ap1: 40-20
  koepi-ap2: 44-20
  koepi-ap3: 36-20
  koepi-ap4: 40-20
  koepi-ap5: 36-20

location__channel_assignments_11g_standard__to_merge:
  koepi-ap1: 6-20
  koepi-ap2: 11-20
  koepi-ap3: 1-20
  koepi-ap4: 6-20
  koepi-ap5: 1-20
