#!/bin/bash

IMAGEBUILDER_PATH="https://downloads.openwrt.org/snapshots/targets/ath79/generic"


IMAGEBUILDER_FILE="openwrt-imagebuilder-ath79-generic.Linux-x86_64.tar.xz"

PROFILE="tplink_eap225-outdoor-v1"
PACKAGES=" mtr tcpdump"
PACKAGES+=" luci-ssl"
PACKAGES+=" luci-app-statistics collectd-mod-uptime collectd-mod-ping"
PACKAGES+=" nftables kmod-nft-bridge"
PACKAGES+=" -ppp -ppp-mod-pppoe"
PACKAGES+=" -wpad-basic-wolfssl hostapd-openssl"

DISABLED_SERVICES="dnsmasq odhcpd firewall"

rm -rf openwrt* builder
wget "$IMAGEBUILDER_PATH/$IMAGEBUILDER_FILE"
tar -xJf "$IMAGEBUILDER_FILE"
rm "$IMAGEBUILDER_FILE"

mv openwrt* builder

mkdir -p builder/files
cp -r etc builder/files

cd builder

make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" DISABLED_SERVICES="$DISABLED_SERVICES" FILES=files/
