#!/bin/sh

. /lib/functions.sh

log() {
    local msg="$1"
    logger -t airmax_dfs_reset -s "$msg"
}

reset_dfs() {                                                         
    local target="$1"
    local username="$2"
    local password="$3"
    local _cmd="/usr/etc/rc.d/rc.softrestart force"
    DROPBEAR_PASSWORD="$password" ssh -y $username@$target "$_cmd"
}  

get_running_freq() {
    local target="$1"
    local username="$2"
    local password="$3"
    local _cmd="iwconfig ath0 | grep Frequency | awk -F ':' '{print \$3}' | awk '{print \$1}' | sed 's/\.//'"
    raw=$(DROPBEAR_PASSWORD="$password" ssh -y $username@$target "$_cmd")000
    echo ${raw:0:4} # Small hack, as Frequency is returned in GHz
}

get_target_freq() {                                                                                                                                                                                               
    local target="$1"                                                                                                                                                                                              
    local username="$2"                                                                                                                                                                                            
    local password="$3"                                                                                                                                                             
    local _cmd="grep 'radio.1.freq' /tmp/system.cfg | awk -F '=' '{ print \$2}'"
    DROPBEAR_PASSWORD="$password" ssh -y $username@$target "$_cmd"
} 

check_dfs() {
    local target="$1"
    local username="$2"
    local password="$3"
    local check_only="4"

    local running_freq=$(get_running_freq $target $username $password)
    local target_freq=$(get_target_freq $target $username $password)                                                                                                                                             
    log "Running freq: $running_freq - Target freq: $target_freq"

    [[ "$running_freq" == "$target_freq" ]]
}


reset_allowed() {
    local daytime_limit="$1"
    local start="$(echo $daytime_limit | awk -F '-' '{print $1'})"
    local end="$(echo $daytime_limit | awk -F '-' '{print $2'})"
    local cur="$(date +%H)"
    [ "$cur" -ge "$start" ] && [ "$cur" -le "$end" ]
}

handle_device() {
    local device="$1"
    config_get target "$device" target
    config_get username "$device" username
    config_get password "$device" password
    config_get daytime_limit "$device" daytime_limit "0-23"

    log "Checking Device $device"
    if check_dfs $target $username $password; then
        log "Frequency is matching. No radar event fired"
    else
	log "Frequency doesnt match. Looks like DFS activity :("
        if reset_allowed $daytime_limit; then
            log "Initiating reset"
            reset_dfs $target $username $password
            log "Exiting - Resetting a single device at a time is enough"
            exit 0
        else
            log "Resetting is forbidden at this daytime"
        fi
    fi
}

config_load airmax
config_foreach handle_device device
