---
exclude_paths:
  - ../.github
  - ../.git
  - ../venv

warn_list:
  - literal-compare
  - no-changed-when
  - command-instead-of-shell
  - command-instead-of-module

skip_list:
  - fqcn
  - fqcn-builtins
  - experimental
  - template-instead-of-copy
  - var-naming[no-role-prefix]
