---
ipv6_prefix: "2001:bf7:830:8b00::/56"

networks:
  - vid: 20
    role: mesh
    name: mesh_scharni
    prefix: 10.31.52.237/32
    ipv6_subprefix: -3
    mesh_metric: 2048
    mesh_ap: colbe15-ap1
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.84.128/26
    ipv6_subprefix: 0
    assignments:
      colbe15-core: 1

  - vid: 41
    role: dhcp
    name: home
    no_corerouter_dns_record: true
    inbound_filtering: true
    enforce_client_isolation: false
    untagged: true
    prefix: 10.31.93.128/26
    ipv6_subprefix: 2
    assignments:
      colbe15-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.84.192/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      colbe15-core: 1
      colbe15-ap1: 2

location__channel_assignments_11a_standard__to_merge:
  colbe15-core: 48-20
  colbe15-ap1: 36-20

location__wireless_profiles__to_merge:
  - name: colbe15
    devices:
      - radio: 11a_standard
        legacy_rates: false
        country: DE
      - radio: 11g_standard
        legacy_rates: false
        country: DE

    ifaces:
      - mode: ap
        ssid: colbe15.freifunk.net
        encryption: none
        network: dhcp
        radio: [11a_standard, 11g_standard]
        ifname_hint: ff

      - mode: ap
        ssid: colbe15.freifunk.net Encrypted
        hidden: true
        encryption: owe
        network: dhcp
        radio: [11a_standard, 11g_standard]
        ifname_hint: ffowe
        ieee80211w: 1

      - mode: ap
        ssid: colbe15-home.freifunk.net
        encryption: sae-mixed
        key: 'file:/root/wifi_pass'
        network: home
        radio: [11a_standard, 11g_standard]
        ifname_hint: home

      - mode: mesh
        mesh_id: Mesh-Freifunk-Berlin
        radio: [11a_standard, 11g_standard]
        mcast_rate: 12000
        mesh_fwding: 0
        ifname_hint: mesh
