---
ipv6_prefix: "2001:bf7:750:1200::/56"

networks:
  - vid: 111
    role: mesh
    name: mesh_segen
    prefix: 10.230.23.141/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 112
    role: mesh
    name: mesh_perleberger36
    prefix: 10.230.23.142/32
    ipv6_subprefix: -2
    ptp: true

  - vid: 113
    role: mesh
    name: mesh_scherer8
    prefix: 10.230.23.143/32
    ipv6_subprefix: -3
    ptp: true

  - vid: 114
    role: mesh
    name: mesh_nord
    prefix: 10.230.23.144/32
    ipv6_subprefix: -4

  - vid: 115
    role: mesh
    name: mesh_chris
    prefix: 10.230.23.145/32
    ipv6_subprefix: -5
    ptp: true

  - vid: 116
    role: mesh
    name: mesh_jup
    prefix: 10.230.23.146/32
    ipv6_subprefix: -6
    ptp: true

  - vid: 117
    role: mesh
    name: mesh_ost
    prefix: 10.230.23.147/32
    ipv6_subprefix: -7

  - vid: 118
    role: mesh
    name: mesh_sued
    prefix: 10.230.23.148/32
    ipv6_subprefix: -8

  - vid: 119
    role: mesh
    name: mesh_fardf
    prefix: 10.230.23.149/32
    ipv6_subprefix: -9
    mesh_metric_lqm: ['default 0.2'] # prefer moabit uplink
    ptp: true

  - vid: 128
    role: mesh
    name: mesh_west
    prefix: 10.230.23.158/32
    ipv6_subprefix: -28

  - vid: 104
    role: dhcp
    prefix: 10.230.23.152/29
    ipv6_subprefix: 0
    untagged: true
    assignments:
      bht-core: 1

  - vid: 102
    role: mgmt
    prefix: 192.168.190.0/24
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      bht-core: 1
      bht-er1: 2
      bht-er2: 3
      bht-segen: 111
      bht-perleberger36: 112
      bht-scherer8: 113
      bht-nord: 114
      bht-chris: 115
      bht-jup: 116
      bht-ost: 117
      bht-sued: 118
      bht-fardf: 119
      bht-west: 128
