---
ipv6_prefix: "2001:bf7:830:4c00::/56"

# mesh ips: 10.31.77.192/30
networks:
  - vid: 10
    role: mesh
    name: mesh_sama
    prefix: 10.31.77.192/32
    ipv6_subprefix: -1
    ptp: true

  - vid: 20
    role: mesh
    name: mesh_core_2ghz
    prefix: 10.31.77.193/32
    ipv6_subprefix: -2
    mesh_ap: gub37-core
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 21
    role: mesh
    name: mesh_core_5ghz
    prefix: 10.31.77.194/32
    ipv6_subprefix: -3
    mesh_ap: gub37-core
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    untagged: true
    prefix: 10.31.114.128/25
    ipv6_subprefix: 0
    assignments:
      gub37-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.77.160/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      gub37-core: 1
      gub37-sama: 2
