#!/bin/sh /etc/rc.common

# Due to the need to change the config file frequently with adding
# and removing new WireGuard tunnels, we strain the flash. On boot,
# we symlink those config files to /var/run/ like done with other
# config files to reduce the load on the flash rom.
#
# Since the ansible images are self-contained the actual config is
# written contained in the read-only /rom/. All changes we add, are
# just for the tunnels, and those tunnels are dynamic and should not
# survive a reboot. That is why we copy the config file back from the
# /rom/ instead of /tmp/run/.
#
# In the case of powercycle, a broken symlink will also result in copying
# the config from the rom again.
#
# On systems without flash, e.g. x86, no /rom/ is existing and no symlink
# is happening.
#

START=11
STOP=89

boot() {
    # symlink babeld
    if ([ ! -L "/etc/config/babeld" ] || [ ! -e "/etc/config/babeld" ]) && [ -f "/rom/etc/config/babeld" ]; then
        cp /rom/etc/config/babeld /var/run
        rm /etc/config/babeld
        ln -s /var/run/babeld /etc/config/babeld
    fi

    # symlink olsrd
    if ([ ! -L "/etc/config/olsrd" ] || [ ! -e "/etc/config/olsrd" ]) && [ -f "/rom/etc/config/olsrd" ]; then
        cp /rom/etc/config/olsrd /var/run
        rm /etc/config/olsrd
        ln -s /var/run/olsrd /etc/config/olsrd
    fi
}

stop() {
    # replace symlink with config from read-only rom
    if [ -L "/etc/config/babeld" ] && [ -f "/rom/etc/config/babeld" ]; then
        rm /etc/config/babeld
        cp /rom/etc/config/babeld /etc/config/babeld
    fi

    # replace symlink with config from read-only rom
    if [ -L "/etc/config/olsrd" ] && [ -f "/rom/etc/config/olsrd" ]; then
        rm /etc/config/olsrd
        cp /rom/etc/config/olsrd /etc/config/olsrd
    fi
}
