---
ipv6_prefix: "2001:bf7:830:6700::/56"

# Rio-Reiser got following prefixes:
# Router: 10.31.134.0/27
# --MGMT: 10.31.134.0/28
# --MESH: 10.31.134.16/28 {as /32}
# --DHCP: 10.31.135.0/24

networks:
  - vid: 10
    role: mesh
    name: mesh_emma
    prefix: 10.31.134.16/32
    ipv6_subprefix: -1

  - vid: 11
    role: mesh
    name: mesh_simeon
    prefix: 10.31.134.17/32
    ipv6_subprefix: -2

  - vid: 20
    role: mesh
    name: mesh_rio
    prefix: 10.31.134.18/32
    ipv6_subprefix: -3
    mesh_metric: 2048
    mesh_ap: rio-sxt
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 21
    role: mesh
    name: mesh_ubnt
    prefix: 10.31.134.19/32
    ipv6_subprefix: -4
    mesh_metric: 2048
    mesh_ap: rio-ubnt
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.135.0/24
    ipv6_subprefix: 0
    assignments:
      rio-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.134.0/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      rio-core: 1
      rio-poe: 2
      rio-emma: 3
      rio-simeon: 4
      rio-sxt: 14
      rio-ubnt: 13

location__channel_assignments_11a_standard__to_merge:
  rio-sxt: 36-20
  rio-ubnt: 40-20
