---
ipv6_prefix: "2001:bf7:830:b300::/58"

# 10.31.177.160/27
# Dragonerareal 2001:bf7:830:b300::/56
#   Buero               2001:bf7:830:b300::/58
#   Dorfplatz           2001:bf7:830:b340::/58
#   Rathausblock Miami  2001:bf7:830:b380::/58
#   Adlerhalle          2001:bf7:830:b3c0::/58
# DHCP: 10.31.177.160/27
# UPLINK: 10.31.23.112/30
# MESH: 10.31.19.45 10.31.19.46 10.31.19.47

networks:
  - vid: 10
    name: mesh_rhxb
    role: mesh
    prefix: 10.31.23.112/30
    ipv6_subprefix: -1
    metric: 1024
    ptp: true
    assignments:
      dragonkiez-buero: 1
      dragonkiez-buero-rhxb: 2

  - vid: 40
    role: dhcp
    untagged: true
    inbound_filtering: false
    enforce_client_isolation: false
    prefix: 10.31.177.160/27
    ipv6_subprefix: 0
    assignments:
      dragonkiez-buero: 1

location__wireless_profiles__to_merge:
  - name: dragonkiez_buero
    devices:
      - radio: 11a_standard
        legacy_rates: false
        country: DE
      - radio: 11g_standard
        legacy_rates: false
        country: DE

    ifaces:
      - mode: ap
        ssid: kiezraum2.berlin.freifunk.net
        encryption: none
        network: dhcp
        radio: [11a_standard, 11g_standard]
        ifname_hint: ff
