---
ipv6_prefix: '2001:bf7:830:2600::/56'


# Mesh: 10.31.114.0/28
networks:
  - vid: 20
    role: mesh
    name: mesh_core
    prefix: 10.31.114.0/32
    ipv6_subprefix: -1
    mesh_metric: 1024
    mesh_ap: huette-core
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 21
    role: mesh
    name: mesh_huette
    prefix: 10.31.114.1/32
    ipv6_subprefix: -2
    mesh_metric: 1024
    mesh_ap: huette-ap1
    mesh_radio: 11a_standard
    mesh_iface: mesh

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.113.128/25
    ipv6_subprefix: 0
    assignments:
      huette-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.112.112/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      huette-core: 1
      huette-ap1: 2

location__channel_assignments_11a_standard__to_merge:
  huette-core: 36-40-19                                # 19 dBm + 4 dBi gain = 23 dBm (with standard antenna)
  huette-ap1: 44-40-8                                  # 8 dBm + 15 dBi gain = 23 dBm (with UMA-D antenna)

location__channel_assignments_11g_standard__to_merge:
  huette-core: 13-20-18                                # 18 dBm + 2 dBi gain = 20 dBm (with standard antenna)
  huette-ap1: 13-20-13                                 # 13 dBm + 10 dBi gain = 23 dBm (with UMA-D antenna)

#
# Devolo Powerline adapters:
# - huette-plc1 fe80::babe:f4ff:feae:746a%eth0
# - huette-plc2 fe80::babe:f4ff:feae:7384%eth0
#
# Their web interfaces can be reached by SSH port forwarding:
# - ssh -L '8080:[fe80::babe:f4ff:feae:7384%eth0]:80' root@huette-core.olsr
# - firefox localhost:8080
# - curl localhost:8080/assets/data.cfl
#
