---

snmp_devices:
  # TODO: Create a Gigabeam LR SNMP profile and use it for segen-saarbr
  # - hostname: segen-saarbr
  #   address: 10.31.6.10
  #   snmp_profile: airos_8

  - hostname: segen-f2a
    address: 10.31.6.11
    snmp_profile: airos_8

  - hostname: segen-mabb
    address: 10.31.6.12
    snmp_profile: airos_8

  - hostname: segen-sw
    address: 10.31.6.13
    snmp_profile: airos_6

  - hostname: segen-bht
    address: 10.31.6.14
    snmp_profile: airos_8

  - hostname: segen-k12
    address: 10.31.6.15
    snmp_profile: airos_8

  - hostname: segen-no
    address: 10.31.6.16
    snmp_profile: airos_6

  - hostname: segen-wsee
    address: 10.31.6.17
    snmp_profile: airos_6

  - hostname: segen-n-5ghz
    address: 10.31.6.20
    snmp_profile: airos_6

  - hostname: segen-o-5ghz
    address: 10.31.6.21
    snmp_profile: airos_6

  - hostname: segen-s-5ghz
    address: 10.31.6.22
    snmp_profile: airos_6

  - hostname: segen-w-5ghz
    address: 10.31.6.23
    snmp_profile: airos_6
