---

# IPv4 10.31.156.0/24
# IPv6 2001:bf7:830:a600::/56

ipv6_prefix: "2001:bf7:830:a600::/56"

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.156.0/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      gruni73-core: 1
      gruni73-switch: 2
      # 5ghz uplink
      gruni73-sama: 5
      gruni73-zwingli: 6
      # local nearfield aps 5ghz
      gruni73-nf-o-5ghz: 13
      gruni73-nf-s-5ghz: 14
      gruni73-nf-w-5ghz: 15

  - vid: 40
    role: dhcp
    prefix: 10.31.156.128/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      gruni73-core: 1

  # 10.31.156.32/27 Mesh Prefix (32)
  # 11s mesh 5ghz
  - vid: 18
    role: mesh
    name: mesh_11s_o5
    prefix: 10.31.156.40/32
    ipv6_subprefix: -6
    mesh_metric: 1024
    mesh_ap: gruni73-nf-o-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4                    # penalty on wild meshing
  - vid: 19
    role: mesh
    name: mesh_11s_s5
    prefix: 10.31.156.41/32
    ipv6_subprefix: -7
    mesh_metric: 1024
    mesh_ap: gruni73-nf-s-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4                    # penalty on wild meshing
  - vid: 20
    role: mesh
    name: mesh_11s_w5
    prefix: 10.31.156.42/32
    ipv6_subprefix: -8
    mesh_metric: 1024
    mesh_ap: gruni73-nf-w-5ghz
    mesh_radio: 11a_standard
    mesh_iface: mesh
    mesh_metric_lqm:
      - default 0.4                    # penalty on wild meshing

location__channel_assignments_11a_standard__to_merge:
  gruni73-nf-o-5ghz: 136-20-14                          # EIRP 30dB - Antenna 19dB + Cable loss 3dB = 14dB
  gruni73-nf-s-5ghz: 36-20-7                            # EIRP 23dB - Antenna 19dB + Cable loss 3dB = 7dB
  gruni73-nf-w-5ghz: 140-20-14                          # EIRP 30dB - Antenna 19dB + Cable loss 3dB = 14dB
