---
ipv6_prefix: "2001:bf7:800:f00::/56"  # aus Berlin

# got following prefixes:
# Router: ###.###.##.##
# --DHCP: 10.30.99.0/25
# --MESH: 10.30.96.32/29
# --MGMT: 10.30.96.40/29

# --UPLK: 10.31.40.124/30 # config-wizard aus Berlin

networks:

  - vid: 20
    role: mesh
    name: mesh_nno
    prefix: 10.30.96.43/32
    ipv6_subprefix: -1
    mesh_metric: 1024
    mesh_ap: fffw-lebenshilfe-nno-ap-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 21
    role: mesh
    name: mesh_nw
    prefix: 10.30.96.44/32
    ipv6_subprefix: -2
    mesh_metric: 1024
    mesh_ap: fffw-lebenshilfe-nw-ap-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 22
    role: mesh
    name: mesh_sso
    prefix: 10.30.96.45/32
    ipv6_subprefix: -3
    mesh_metric: 1024
    mesh_ap: fffw-lebenshilfe-sso-ap-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh

  - vid: 23
    role: mesh
    name: mesh_ono
    prefix: 10.30.96.46/32
    ipv6_subprefix: -4
    mesh_metric: 1024
    mesh_ap: fffw-lebenshilfe-ono-ap-2ghz
    mesh_radio: 11g_standard
    mesh_iface: mesh

  # UPLK
  - vid: 50
    role: uplink
    untagged: true

  - role: tunnel
    ifname: ts_wg0
    mtu: 1280
    prefix: 10.31.40.125/32
    wireguard_port: 51820

  - role: tunnel
    ifname: ts_wg1
    mtu: 1280
    prefix: 10.31.40.126/32
    wireguard_port: 51821

  - vid: 42
    role: mgmt
    prefix: 10.30.96.32/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      fffw-lebenshilfe-core: 1
      # fffw-lebenshilfe-switch: 2
      fffw-lebenshilfe-nw-ap-2ghz: 3
      fffw-lebenshilfe-nno-ap-2ghz: 4
      fffw-lebenshilfe-sso-ap-2ghz: 5
      fffw-lebenshilfe-ono-ap-2ghz: 6

  - vid: 40
    role: dhcp
    prefix: 10.30.99.0/25
    ipv6_subprefix: 0
    assignments:
      fffw-lebenshilfe-core: 1

location__channel_assignments_11g_standard__to_merge:
  # ap-name: Channel  Bandwidth  tx-Power
  fffw-lebenshilfe-nno-ap-2ghz: 1-20
  fffw-lebenshilfe-nw-ap-2ghz: 6-20
  fffw-lebenshilfe-sso-ap-2ghz: 11-20
  fffw-lebenshilfe-ono-ap-2ghz: 6-20

...
