---
ipv6_prefix: "2001:bf7:830:a900::/56"

# mesh_prefix: 10.31.155.192/29

networks:
  - vid: 42
    role: mgmt
    prefix: 10.31.155.224/27
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      newyorck-core: 1
      newyorck-switch: 2
      newyorck-ap1: 3
      newyorck-ap2: 4
      newyorck-ap3: 5
      newyorck-ap4: 6
      newyorck-ap5: 7
      newyorck-ap6: 8

  - vid: 40
    role: dhcp
    prefix: 10.31.160.0/25
    ipv6_subprefix: 0
    inbound_filtering: true
    enforce_client_isolation: true
    assignments:
      newyorck-core: 1

  - vid: 50
    name: vpn_5g
    role: uplink

  - role: tunnel
    ifname: ts_wg0
    mtu: 1280
    prefix: 10.31.155.192/32
    wireguard_port: 51820

  - role: tunnel
    ifname: ts_wg1
    mtu: 1280
    prefix: 10.31.155.193/32
    wireguard_port: 51821
