#!/bin/sh

logger "starting collectd dhcp-leases-addon"

HOSTNAME="${COLLECTD_HOSTNAME}"
INTERVAL="${COLLECTD_INTERVAL}"
INTERVAL="${INTERVAL/\.[0-9]*}"

LEASEFILE="/tmp/dhcp.leases"


while sleep $INTERVAL; do
  LEASES=$(cat ${LEASEFILE} | wc -l)
  echo "PUTVAL \"$HOSTNAME/exec-dhcp/gauge-dhcp-leases\" interval=$INTERVAL N:$LEASES"
  logger "PUTVAL \"$HOSTNAME/exec-dhcp/gauge-dhcp-leases\" interval=$INTERVAL N:$LEASES"
done
