---
ipv6_prefix: "2001:bf7:830:b00::/56"

# 10.31.92.0/26 2001:bf7:830:b00::/56
# DHCP: 10.31.92.32/27
# MGMT: 10.31.92.0/28
# MESH: 10.31.92.16/28

networks:
  - vid: 10
    role: mesh
    name: mesh_emma
    prefix: 10.31.92.16/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.92.32/27
    ipv6_subprefix: 0
    untagged: true
    assignments:
      walde-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.92.0/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      walde-core: 1
      walde-emma: 2
