---
ipv6_prefix: '2001:bf7:760:2b00::/56'

# got following prefixes:
# Router:  10.31.157.128/26
# --DHCP:  10.31.157.128/27
# --MESH:  10.31.157.160/28
# --MGMT:  10.31.157.176/28

networks:
# DHCP
  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.157.128/27
    ipv6_subprefix: 0
    assignments:
      k12-haus4-core: 1
      k12-haus4-hirschhof: 2

# MESH - 5 GHz 802.11s
  - vid: 20
    role: mesh
    name: mesh_5ghz
    prefix: 10.31.157.160/32
    ipv6_subprefix: -1
    mesh_ap: k12-haus4-core
    mesh_radio: 11a_standard
    mesh_iface: mesh

# MESH - 2.4 GHz 802.11s
  - vid: 21
    role: mesh
    name: mesh_2ghz
    prefix: 10.31.157.161/32
    ipv6_subprefix: -2
    # make mesh_metric(s) for 2GHz worse than 5GHz
    mesh_metric: 1024
    mesh_metric_lqm: ['default 0.8']
    mesh_ap: k12-haus4-core
    mesh_radio: 11g_standard
    mesh_iface: mesh

# MESH - 2.4 GHz 802.11s - Hirschhof
  - vid: 22
    role: mesh
    name: mesh_hirsch
    prefix: 10.31.157.162/32
    ipv6_subprefix: -3
    mesh_ap: k12-haus4-hirschhof
    mesh_radio: 11g_standard
    mesh_iface: mesh

# MGMT
  - vid: 42
    role: mgmt
    prefix: 10.31.157.176/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      #10.31.157.177/32
      k12-haus4-core: 1
      #10.31.157.178/32
      k12-haus4-hirschhof: 2

# AP-id, wifi-channel, bandwidth, txpower
location__channel_assignments_11a_standard__to_merge:
  k12-haus4-core: 44-40

location__channel_assignments_11g_standard__to_merge:
  k12-haus4-core: 13-20
  k12-haus4-hirschhof: 13-20
