---
ipv6_prefix: "2001:bf7:820:e00::/56"

# Klunker got following prefixes: 10.31.71.144/28
# --MGMT: 10.31.71.144/29
# --MESH: 10.31.71.152/29
# --DHCP: 10.31.178.0/25

networks:
  - vid: 10
    role: mesh
    name: mesh_rhnk
    prefix: 10.31.71.152/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.178.0/25
    ipv6_subprefix: 0
    assignments:
      klunker-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.71.144/29
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      klunker-core: 1
      klunker-poe: 2
      klunker-rhnk: 3
