---
name: Check missing mac_overrides

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  check-mac-override-missing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run mac_override missing check
        run: |
          ./.github/checks/check-mac-override-missing.sh
