---
name: Check for duplicate addresses

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  check-address-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run address duplicate check
        run: |
          ./.github/checks/check-address-duplicates.sh
