---
name: Config Run

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write # required for artifacts
  actions: read

jobs:
  build:
    name: Ansible Config Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install -r requirements.txt --upgrade pip

      - name: Determine changed hosts
        env:
          BEFORE: ${{ github.event.before }}
        run: |
          LIMIT=$(./.github/scripts/changed-hosts.sh)
          echo "Building for $LIMIT"
          echo "LIMIT=$LIMIT" >> "$GITHUB_ENV"

      - name: Build changed hosts
        run: |
          if [ -n "${LIMIT}" ]; then
            ansible-playbook play.yml --limit "${LIMIT}"
          fi
          mkdir -p ./tmp/configs

      - name: Create tar from configs folder
        run: |
          # create a tar containing the configs, as files with colons might be created which are rejected by upload-artifact
          # upload-artifact rejects all files that might cause issues with file systems that do not support all characters
          tar -cvf ./tmp/configs.tar ./tmp/configs/

      - name: Store build output
        uses: actions/upload-artifact@v5
        with:
          name: ansibleconfigs
          path: |
            ./tmp/configs.tar
