---
name: Image Run

# This workflow generates images of changed locations on user request.
# Add the label 'build_image' to the PR to trigger a new image run.
# This will run once. To trigger the workflow again you have to remove
# the label first to add it again.

on:
  pull_request:
    types:
      - "labeled"

permissions:
  contents: write # required for artifacts
  actions: read
  pull-requests: write # required for commenting

jobs:
  build:
    name: Ansible Image Run
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'build_image' }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install -r requirements.txt --upgrade pip

      - name: Determine changed hosts
        env:
          BEFORE: ${{ github.event.before }}
        run: |
          LIMIT=$(./.github/scripts/changed-hosts.sh)
          echo "Building for $LIMIT"
          echo "LIMIT=$LIMIT" >> "$GITHUB_ENV"

      - name: Build changed hosts
        run: |
          if [ -n "${LIMIT}" ]; then
            ansible-playbook play.yml --limit "${LIMIT}" --tags image
          fi
          mkdir -p ./tmp/images

      - name: Create tar from configs folder
        run: |
          # create a tar containing the configs, as files with colons might be created which are rejected by upload-artifact
          # upload-artifact rejects all files that might cause issues with file systems that do not support all characters
          tar -cvf ./tmp/images.tar ./tmp/images/

      - name: Store build output
        id: artifact-upload-step
        uses: actions/upload-artifact@v5
        with:
          name: ansibleimages
          path: |
            ./tmp/images.tar

      - name: Comment link to artifacts
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hey :wave:
            I am building images because you added the label `build_image`.
            You can find the output [here](${{ steps.artifact-upload-step.outputs.artifact-url }}). If you need new images just add the label again.
