---
name: ShellCheck Lint
on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  build:
    name: Lint ShellCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint ShellCheck
        uses: ludeeus/action-shellcheck@master
