---
name: Wikiupdate
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt install python3

      - name: Install dependencies
        run: pip3 install -r requirements.txt --upgrade pip

      - name: Determine changed locations
        run: |
            CHANGED_LOCATIONS=$(git diff ${{ github.event.before }}..${{ github.event.after }} --diff-filter=d --name-only | grep 'locations/' | sed 's/locations\/\(.*\)\.yml/location_\1/' | sed -z 's/-/_/g;s/\n/,/g;s/,$//')
            echo "Updating for changed locations: $CHANGED_LOCATIONS"
            echo "CHANGED_LOCATIONS=$CHANGED_LOCATIONS" >> "$GITHUB_ENV"

      - name: Update wiki.freifunk.net
        run: |
          if [ -n "${CHANGED_LOCATIONS}" ]; then
            ansible-playbook play.yml --tags wiki --limit "$CHANGED_LOCATIONS" ||true
          else
            echo "No locations were changed. Skipping update"
          fi
