---
name: Yaml Lint
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Yaml Files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .config/yaml-lint.yml
