#!/bin/bash

IMAGEBUILDER_PATH="https://downloads.openwrt.org/releases/19.07.5/targets/mpc85xx/generic"
IMAGEBUILDER_FILE="openwrt-imagebuilder-19.07.5-mpc85xx-generic.Linux-x86_64.tar.xz"
FALTER_REPO="src/gz openwrt_falter http://download-master.berlin.freifunk.net/falter-feed/19.07/powerpc_8540/falter/"

PROFILE="tl-wdr4900-v1"
PACKAGES=" mtr tcpdump"
PACKAGES+=" luci-ssl"
PACKAGES+=" luci-app-statistics collectd-mod-uptime collectd-mod-ping collectd-mod-olsrd collectd-mod-exec"
PACKAGES+=" olsrd olsrd-mod-arprefresh olsrd-mod-dyn-gw olsrd-mod-jsoninfo olsrd-mod-nameservice olsrd-mod-txtinfo olsrd-mod-watchdog"
PACKAGES+=" luci-app-olsr luci-app-olsr-services"
PACKAGES+=" luci-mod-falter falter-berlin-fix-luci"
PACKAGES+=" luci-app-falter-owm luci-app-falter-owm-ant luci-app-falter-owm-cmd luci-app-falter-owm-gui"
PACKAGES+=" -ppp -ppp-mod-pppoe"

#Below packages from Zwingli
PACKAGES+=" alfred batctl kmod-batman-adv oonf-olsrd2"
DISABLED_SERVICES="olsrd6"

rm -rf openwrt* builder
wget "$IMAGEBUILDER_PATH/$IMAGEBUILDER_FILE"
tar -xJf "$IMAGEBUILDER_FILE"
rm "$IMAGEBUILDER_FILE"

mv openwrt* builder

mkdir -p builder/files
cp -r etc builder/files

INSTR_SET=$(grep "openwrt_base" builder/repositories.conf | awk -F'/' '{print $8}')
echo "$FALTER_REPO" >> builder/repositories.conf

cd builder

make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" DISABLED_SERVICES="$DISABLED_SERVICES" FILES=files/
