---
ipv6_prefix: "2001:bf7:830:3000::/56"

# 10.31.92.64/26 2001:bf7:830:3000::/56
# DHCP: 10.31.92.64/27
# MGMT: 10.31.92.96/28
# MESH: 10.31.92.112/28

networks:
  - vid: 10
    role: mesh
    name: mesh_rhxb
    prefix: 10.31.92.112/32
    ipv6_subprefix: -1

  - vid: 40
    role: dhcp
    inbound_filtering: true
    enforce_client_isolation: true
    prefix: 10.31.92.32/27
    ipv6_subprefix: 0
    untagged: true
    assignments:
      dragon-core: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.92.96/28
    gateway: 1
    dns: 1
    ipv6_subprefix: 1
    assignments:
      dragon-core: 1
      dragon-rhxb: 2
